apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlingo-deployment
  labels:
    app: hlingoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hlingoapp
  template:
    metadata:
      labels:
        app: hlingoapp
    spec:
      containers:
      - name: hlingoapp
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8000
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: hlingo-config
                key: APP_NAME
          - name: DB_HOST 
            valueFrom:
              configMapKeyRef:
                name: hlingo-config
                key: DB_HOST 
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: hlingo-config
                key: DB_NAME
          - name: DB_PORT 
            valueFrom:
              configMapKeyRef:
                name: hlingo-config
                key: DB_PORT
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DB_USER
