apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlingo-deployment
  labels:
    app: hlingoapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hlingoapp
  template:
    metadata:
      labels:
        app: hlingoapp
    spec:
      containers:
      - name: hlingoapp
        image: gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
