name: Create Release
on:
  push:
    branches:
      - main

jobs: 
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          github-token: ${{ secrets.github_token }}
      - name: create release
        uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.github_token }}
          tag_name: ${{  steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          #body: ${{ steps.changelog.outputs.clean_changelog }}
